---
- name: Ensure required packages are installed
  ansible.builtin.package:
    name:
      - curl
      - tar
    state: present

- name: Download VSCode server
  ansible.builtin.get_url:
    url: "https://code.visualstudio.com/sha/download?build=stable&os=cli-alpine-x64"
    dest: "/tmp/vscode_cli.tar.gz"
    mode: '0755'
    force: yes

- name: Create /usr/local/bin directory if not exists
  ansible.builtin.file:
    path: "/usr/local/bin"
    state: directory
    mode: '0755'

- name: Extract VSCode server
  ansible.builtin.unarchive:
    src: "/tmp/vscode_cli.tar.gz"
    dest: "/usr/local/bin"
    remote_src: yes

- name: Clean up temporary files
  ansible.builtin.file:
    path: "/tmp/vscode_cli.tar.gz"
    state: absent
