galaxy_info:
  role_name: ssh
  namespace: gonzfe05
  author: Fernando Gonzalez
  description: Installs and sets up ssh

  license: license (GPL-2.0-or-later, MIT, etc)

  min_ansible_version: "2.1"

  galaxy_tags: ["ssh"]

dependencies: []