---
- name: Converge
  hosts: instance
  become: yes
  vars:
    personal_folder: /tmp/test-personal
    work_folder: /tmp/test-work
  pre_tasks:
    - name: Install git (required for repos role)
      apt:
        name: git
        state: present
        update_cache: yes
    
    - name: Create test user for repos testing
      user:
        name: testuser
        home: /home/testuser
        shell: /bin/bash
        create_home: yes
    
    - name: Create test directories
      file:
        path: "{{ item }}"
        state: directory
        owner: testuser
        group: testuser
        mode: '0755'
      loop:
        - "{{ personal_folder }}"
        - "{{ work_folder }}"
  
  tasks:
    # Test git functionality without using private repos
    - name: Test git clone with public repo (simulating repos role behavior)
      git:
        repo: 'https://github.com/octocat/Hello-World.git'
        dest: "{{ personal_folder }}/test-hello-world"
        update: yes
        force: yes
      become_user: testuser
      register: git_clone_result
    
    - name: Verify git clone succeeded
      debug:
        msg: "Git clone test successful"
      when: git_clone_result is succeeded
    
    - name: Test that directories exist (repos role requirement)
      stat:
        path: "{{ item }}"
      register: dir_stats
      loop:
        - "{{ personal_folder }}"
        - "{{ work_folder }}"
    
    - name: Verify all required directories exist
      assert:
        that:
          - item.stat.exists
          - item.stat.isdir
        fail_msg: "Required directory does not exist: {{ item.item }}"
      loop: "{{ dir_stats.results }}"
