---
- name: Converge
  hosts: instance
  become: yes
  become_user: root
  roles:
    - role: apt_installs
      vars:
        apt_installs_custom:
          - openssh-client    # SSH client for outbound connections
          - openssh-server    # SSH server for inbound connections (testing server feature)
    - role: users
      vars:
        users:
          - name: aleph
            uid: 1001
            shell: /bin/bash
            comment: "Aleph User"
            groups: "admin,sudo,docker"
            password: ""
    - role: ssh
      vars:
        ssh_server_enabled: true  # Test both client and server functionality
      become: yes
      become_user: aleph
      become_password: ""