---
dependency:
  name: galaxy
driver:
  name: docker
platforms:
  - name: instance
    image: ${MOLECULE_IMAGE:-ubuntu:22.04}
    command: /sbin/init
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    privileged: true
    become: yes
provisioner:
  name: ansible
  lint: |
    set -e
    yamllint .
    ansible-lint
  playbooks:
    converge: converge.yml
scenario:
  name: default
  test_sequence:
    # - lint
    - dependency
    - create
    - prepare
    - converge
    - verify
    - destroy
verifier:
  name: ansible
