---
extends: default

rules:
  # Very lenient rules for existing codebase
  document-start: disable
  comments-indentation: disable
  line-length: disable
  indentation: disable
  brackets: disable
  truthy: disable
  new-line-at-end-of-file: disable
  comments: disable
  empty-lines: disable
  
# Only check critical syntax errors
ignore: |
  .git/
  .vscode/
  scripts/
  credentials/
  tasks/
  .github/