- name: Setup and configure dotfiles and SSH keys
  hosts: localhost
  vars:
    personal: "{{ lookup('env', 'HOME') }}/personal"
  pre_tasks:
    - name: Update Apt
      become: true
      ansible.builtin.apt:
        force_apt_get: true
        update_cache: true
        state: present
      tags:
        - install
        - core
  tasks:
    - name: Include Zsh setup tasks
      ansible.builtin.include_tasks: tasks/zsh-setup.yml
    - name: Include ssh setup tasks
      ansible.builtin.include_tasks: tasks/ssh-setup.yml
#    - include: tasks/git-setup.yml
#    - include: tasks/core-setup.yml
#    - include: tasks/node-setup.yml
#    - include: tasks/npm-packages.yml
#    - include: tasks/slack-setup.yml
#    - include: tasks/personal-projects.yml
#    - include: tasks/nvim-setup.yml
#    - include: tasks/brave.yml
#    - include: tasks/debugger.yml
#    - include: tasks/dotfiles.yml
#    - include: tasks/productivity-tools.yml
#    - include: tasks/lsp.yml
