- name: Setup and configure dotfiles and SSH keys
  hosts: localhost
  pre_tasks:
    - name: Update Apt
      become: true
      ansible.builtin.apt:
        force_apt_get: true
        update_cache: true
        state: present
      tags:
        - install
        - core
  tasks:
    - name: Include Zsh
      ansible.builtin.include_tasks: tasks/zsh-setup.yml
      tags: zsh
    - name: Include ssh
      ansible.builtin.include_tasks: tasks/ssh-setup.yml
      tags:
        - ssh
        - dotfiles
    - name: Include libraries i want
      ansible.builtin.include_tasks: tasks/common.yml
      tags: common-libs
    - name: Include core libraries
      ansible.builtin.include_tasks: tasks/core.yml
      tags:
        - core-libs
        - dotfiles
    - name: Include git
      ansible.builtin.include_tasks: tasks/git-setup.yml
      tags:
        - git
        - dotfiles
    - name: Include tmux
      ansible.builtin.include_tasks: tasks/tmux-setup.yml
      tags: tmux
    - name: Include dotfiles
      ansible.builtin.include_tasks: tasks/dotfiles-setup.yml
      tags: dotfiles

- name: Zsh
  hosts: localhost
  pre_tasks:
    - name: Update Apt
      become: true
      ansible.builtin.apt:
        force_apt_get: true
        update_cache: true
        state: present
      tags:
        - install
        - core
  tasks:
    - name: Include Zsh
      ansible.builtin.include_tasks: tasks/zsh-setup.yml
      tags: zsh