- name: Install dotfiles from my repo
  tags:
    - install
    - dotfiles
    - stow
  block:
    - name: Installing stow
      apt: name=stow
      become: true
    - name: Cloning .dotfiles
      ansible.builtin.git:
        repo: 'git@github.com:gonzfe05/.dotfiles.git'
        dest: "{{ lookup('env', 'HOME') }}/.dotfiles"
        recursive: true
        update: true
        accept_hostkey: true
        force: true
        version: main
      tags:
        - install
        - dotfiles
        - stow
    - name: Ensure ubuntu.sh is executable
      file:
        path: "{{ ansible_env.HOME }}/.dotfiles/ubuntu.sh"
        mode: '0755'
        state: file
    - name: Ensure install.sh is executable
      file:
        path: "{{ ansible_env.HOME }}/.dotfiles/install.sh"
        mode: '0755'
        state: file
    - name: Check if .zshrc file exists
      stat:
        path: "{{ ansible_env.HOME }}/.zshrc"
      register: zshrc_file
    - name: Move .zshrc to .zshrc.backup
      command: "mv {{ ansible_env.HOME }}/.zshrc {{ ansible_env.HOME }}/.zshrc.backup"
      when: zshrc_file.stat.exists
    - name: Stow dotfiles
      shell: cd $HOME/.dotfiles && ./ubuntu.sh
    - name: Set execute permissions on all files in {{ ansible_env.HOME }}/bin
      find:
        paths: "{{ ansible_env.HOME }}/bin"
        recurse: true
        file_type: file
      register: bin_files
    - name: Ensure all files in {{ ansible_env.HOME }}/bin are executable
      file:
        path: "{{ item.path }}"
        mode: '0755'
      loop: "{{ bin_files.files }}"
