---
dependency:
  name: galaxy
driver:
  name: docker
platforms:
  - name: instance
    image: geerlingguy/docker-ubuntu${UBUNTU_MAJOR:-24}${UBUNTU_MINOR:-04}-ansible
    privileged: true
    # become: yes
provisioner:
  name: ansible
  lint: |
    set -e
    yamllint .
    ansible-lint
  env:
    ANSIBLE_VAULT_PASSWORD_FILE: ${ANSIBLE_VAULT_PASSWORD_FILE}
  playbooks:
    converge: converge.yml
scenario:
  name: default
  test_sequence:
    # - lint
    - dependency
    - create
    - prepare
    - converge
    - verify
    - destroy
verifier:
  name: ansible
