---
- name: Verify python role
  hosts: instance
  vars:
    python_version: 3.12
  tasks:
    - name: Check if the Python package is installed
      command: "python --version"
      changed_when: false
      failed_when: python_installed.rc != 0
      register: python_installed

    - name: Ensure Python package is installed
      assert:
        that:
          - python_installed.rc == 0

    - name: Ensure the Python version is correct
      assert:
        that:
          - "'Python {{ python_version }}' in python_installed.stdout"
