---
- name: Verify python role
  hosts: instance
  vars:
    pytohn_version: 3.12
  tasks:
    - name: Check if the Python package is installed
      apt:
        name: "python{{ python_version }}"
        state: present
      register: python_installed

    - name: Ensure Python package is installed
      assert:
        that:
          - python_installed is succeeded

    - name: Verify Python version
      command: "python{{ python_version }} --version"
      register: python_version_output
      changed_when: false

    - name: Ensure the Python version is correct
      assert:
        that:
          - "'Python {{ python_version }}' in python_version_output.stdout"
