---
- name: Prepare instance by installing Ansible
  hosts: all
  become: yes
  tasks:
    - name: Install software-properties-common
      apt:
        name: software-properties-common
        state: present
        update_cache: yes

    - name: Add Ansible PPA
      apt_repository:
        repo: ppa:ansible/ansible
        state: present
        update_cache: yes

    - name: Install Ansible
      apt:
        name: ansible
        state: present
