---
- name: Verify Obsidian installation
  hosts: all
  gather_facts: false
  tasks:

    - name: Check if Obsidian binary is available
      ansible.builtin.command: which obsidian
      register: obsidian_binary
      changed_when: false
      failed_when: obsidian_binary.rc != 0

    - name: Print path to Obsidian binary
      ansible.builtin.debug:
        msg: "Obsidian is installed at {{ obsidian_binary.stdout }}"

    - name: Check if Obsidian desktop entry exists
      ansible.builtin.stat:
        path: /usr/share/applications/obsidian.desktop
      register: obsidian_desktop_entry

    - name: Assert that Obsidian desktop file exists
      ansible.builtin.assert:
        that:
          - obsidian_desktop_entry.stat.exists
        fail_msg: "Obsidian desktop entry is missing!"
        success_msg: "Obsidian desktop entry is present."
