---
- name: Verify Obsidian installation
  ansible.builtin.command: "snap list obsidian"
  register: obsidian_installation
  failed_when: obsidian_installation.rc != 0

- name: Display Obsidian installation status
  ansible.builtin.debug:
    msg: "Obsidian is successfully installed"
  when: obsidian_installation.rc == 0
