---
- name: Converge
  hosts: instance
  become: true
  become_user: root
  roles:
    - role: apt_installs
      vars:
        apt_update_cache: true
        apt_cache_valid_time: 3600
        apt_ppa_custom: []
        apt_upgrade: false
        apt_installs_custom:
          - gnupg
    - role: R
