---
- name: Verify R installation
  hosts: all
  gather_facts: false
  tasks:

    - name: Check that R is installed
      ansible.builtin.command: R --version
      register: r_version
      changed_when: false
      failed_when: r_version.rc != 0

    - name: Print R version
      debug:
        var: r_version.stdout

    - name: Verify the CRAN repository is configured
      ansible.builtin.command: grep -R 'https://cloud.r-project.org/bin/linux/ubuntu.*cran40' /etc/apt/sources.list /etc/apt/sources.list.d/
      register: cran_repo_check
      changed_when: false
      failed_when: cran_repo_check.rc != 0

    - name: Ensure GPG key is present
      ansible.builtin.command: apt-key list
      register: gpg_keys
      changed_when: false
      failed_when: "'marutter@gmail.com' not in gpg_keys.stdout"
