---
- name: Add NVIDIA GPG key
  ansible.builtin.apt_key:
    url: https://nvidia.github.io/libnvidia-container/gpgkey
    state: present
    keyring: /usr/share/keyrings/nvidia-container-toolkit-keyring.gpg

- name: Add NVIDIA Container Toolkit repository
  ansible.builtin.apt_repository:
    repo: "deb [signed-by=/usr/share/keyrings/nvidia-container-toolkit-keyring.gpg] https://nvidia.github.io/libnvidia-container/stable/deb/ nvidia-container-toolkit"
    state: present
    filename: 'nvidia-container-toolkit'

- name: Optionally enable experimental packages
  ansible.builtin.lineinfile:
    path: /etc/apt/sources.list.d/nvidia-container-toolkit.list
    regexp: '^#deb .*/experimental/.*'
    line: 'deb [signed-by=/usr/share/keyrings/nvidia-container-toolkit-keyring.gpg] https://nvidia.github.io/libnvidia-container/experimental/deb/ nvidia-container-toolkit'
    state: present

- name: Update the apt package index
  ansible.builtin.apt:
    update_cache: yes

- name: Install NVIDIA Container Toolkit
  ansible.builtin.apt:
    name: nvidia-container-toolkit
    state: present

- name: Configure NVIDIA Container Runtime for Docker
  ansible.builtin.command:
    cmd: nvidia-ctk runtime configure --runtime=docker
    creates: /etc/docker/daemon.json  # Only run if the daemon.json file is not already present

- name: Restart Docker
  ansible.builtin.systemd:
    name: docker
    state: restarted
