---
- name: Test
  hosts: localhost
  roles:
    - role: apt_installs
      vars:
        apt_ppa_custom:
          - ppa:jonathonf/vim
        apt_installs_custom:
          - openssh-client
          - git
          - zsh
          - tmux
          - stow
          - fzf
          - zip
          - vim
          - xclip
          - vim-gtk
          - sudo
          - clang-12
      become: yes
      become_user: root
      tags: ['core']
    - role: users
      vars:
        users:
          - name: aleph
            uid: 1001
            shell: /bin/bash
            comment: "Aleph User"
            groups: "admin,sudo"
            password: ""
      become: yes
      become_user: root
      tags: ['core']
    - role: ssh
      become: yes
      become_user: aleph
      tags: ['core']
    - role: env_setup
      become: yes
      become_user: aleph
      tags: ['core']
    - role: dotfiles
      become: yes
      become_user: aleph
      tags: ['core']
    - role: node
      become: yes
      become_user: aleph
      tags: ['core']
    - role: aws
      become: yes
      become_user: aleph
      tags: ['aws']
    - role: repos
      become: yes
      become_user: aleph
      tags: ['projects']
    - role: go
      become: yes
      become_user: root
      tags: ['go']
 
