---
- name: Setup ngrok for SSH tunneling
  hosts: localhost
  roles:
    - role: ngrok
      vars:
        # Provide your ngrok authtoken via:
        # 1. Command line: --extra-vars "ngrok_authtoken=YOUR_TOKEN"
        # 2. Environment: --extra-vars "ngrok_authtoken={{ lookup('env', 'NGROK_AUTHTOKEN') }}"
        # 3. Vault file: --extra-vars "@credentials/ngrok_vault.yml" --ask-vault-pass
        ngrok_authtoken: "{{ ngrok_authtoken | default('') }}"
      become: true
      become_user: fer
      tags: ['ngrok']

