---
name: Lint

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  yaml-lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install yamllint
        run: pip install yamllint

      - name: Run yamllint
        run: yamllint .

  ansible-lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install ansible-lint
        run: pip install ansible-lint

      - name: Run ansible-lint on playbooks
        run: |
          find playbooks -name "*.yml" -o -name "*.yaml" | xargs ansible-lint

      - name: Run ansible-lint on roles
        run: |
          find playbooks/roles -mindepth 2 -maxdepth 2 -type d | while read role_dir; do
            if [[ -f "$role_dir/tasks/main.yml" || -f "$role_dir/tasks/main.yaml" ]]; then
              echo "Linting role: $role_dir"
              ansible-lint "$role_dir"
            fi
          done